import Setting from './setting'
import Search from './search'
import Earth from './earth'
import Up from './up'
import People from './people'
import Calendar from './calendar'
import Union from './union'
import Trophy from './trophy'
import Map from './map'
import Heart from './heart'
import Music from './music'
export{Setting,Search,Earth,Up,People,Calendar,Union,Trophy,Map,Heart,Music}