export const File= `Terms of Use
(Updated December 15, 2020)
 These Terms of Use govern the use of the Website at PlayersRecLeague.com, and any successor website thereto (collectively, the “Website”), the mobile application Players Rec League (the “App”) and use of any services provided by World Rec League, Inc., a Delaware corporation ("WRL"), by you or those who act on your behalf. The viewing of the Website and the App or the use of the services provided by the Website and the App by you or those who act on your behalf will constitute agreement by you and those who act on your behalf to all of the terms and conditions provided in these Terms of Use. All references to “you” or “your” below refer to you and those who act on your behalf.
 
ADDITIONAL TERMS AND CONDITIONS REFERENCED OR PROVIDED IN THESE TERMS OF USE ORTHROUGHOUT THE WEBSITE OR THE APP GOVERN YOUR USE OF PARTICULAR FUNCTIONS, FEATURES, INFORMATION, APPLICATIONS, SERVICES AND PRODUCTS, IF ANY, AVAILABLE THROUGH THE WEBSITE AND THE APP.
 Section 1. Use of the Website and the App
The Website is operated by WRL to provide a platform for collaborative participation in sports activities. Any use of the Website or the App by any other person or entity for any other purpose is prohibited. Neither WRL nor any of its members, shareholders, managers, directors, officers, employees, agents, independent contractors, representatives or attorneys bear any liability or responsibility for any such prohibited use.
A currently registered user may access the user’s own specific information and services through the Website and the App. Non-registered Website visitors may only access information of general interest.
 
YOU ACKNOWLEDGE THAT THE PURPOSE OF THE WEBSITE AND THE APP ARE TO PROVIDE INFORMATION ANALYSIS BASED UPON INFORMATION ENTERED BY YOU OR THOSE ACTING ON YOUR BEHALF. ACCORDINGLY, YOU ACKNOWLEDGE AND AGREE THAT WRL IS NOT RESPONSIBLE FOR VERIFYING ANY OF THE ENTERED INFORMATION OR THE ACCURACY THEREOF, AND THAT ANY ERRORS IN THE DATA ENTRY MAY RESULT IN INACCURATE OR MISLEADING RESULTS OR REPORTS.
 
WRL may add services to the Website or the App for use by WRL visitors, or may change the existing services. WRL may make said additions and changes at any time and from time to time with or without notice and for any reason. Your subsequent viewing or use of the Website and/or the App will constitute your agreement to said additions and changes. Any access to the Website or the App to obtain information by automated inquiry devices or programs (other than the App) is strictly prohibited. Using or attempting to use the Website to compete with WRL or to interfere with its business is strictly prohibited. WRL does not accept ideas, concepts, or techniques for new services or products through the Website. If such information is received, it will not be considered confidential nor proprietary, and WRL will be free to use, communicate and exploit such information in any manner whatsoever.
 Section 2. Termination of Access
WRL may, in its sole and absolute discretion, discontinue, suspend or modify your or any other user’s access to the Website or the App (or any portion thereof) at any time with or without notice, and for any reason.
 Section 3. Registration
In order to use the services on the Website or through the App, you will need to register on the Website and create a user account. By registering, you agree to provide accurate and current information about yourself, and further agree to maintain and promptly update your information. If any information provided by you is inaccurate or outdated, or if WRL has reasonable grounds to suspect that such information is inaccurate or outdated, WRL may suspend or terminate your registration and your or any other associated user’s access to the Website or any portion thereof, or through the App any time with or without notice.
 
To register, you will select a password to accompany your user name.  Your user name will be associated with your account. You are responsible for the confidentiality of  names and passwords and for any and all activities and use of the Website by you. Accordingly, you are required and hereby agree to immediately notify WRL of any unauthorized use of any user name or password.
We suggest that as part of your processes to maintain the security of all user names and passwords, you ensure that you and those acting on your behalf log out from the Website or logout from the App immediately after concluding each visit. You may wish to avoid saving any user name or password on any computer or mobile device used to access the Website, especially if it is outside a secure environment.
 
Section 4. Website Changes, Updates, and Content
WRL may, in its sole and absolute discretion at any time and from time to time with or without notice and for any reason, change or update the Website and/or the App, and change, update or delete any content appearing or accessible on the Website or the App and add any content thereto, including without limitation information, graPIcs, service, products, features, functionality, and links (collectively, the "Content").
 Section 5. Ownership of Website, App and Content; Copyrights and Trademarks
The Website, the App and the Content, are protected by United States and international copyright, trademark and other intellectual property laws. All rights in and to the Website, the App and the Content are reserved to WRL. By allowing access to the Website and the App, WRL is not conveying and does not convey to anyone any ownership rights in the Website, the App or in any Content. You are only granted a limited license to reproduce the Content on your computer or mobile device for the purpose of accessing the Website and using the features and services accessible thereon for legitimate purposes, and for the purpose of using the App. You are also granted a license to print reports and other information appearing on your computer screen in the course of using the features and services of the Website and the App.
No other permission is granted in any way to download, modify, reproduce, use, copy or distribute any of the Content. You may not replicate, duplicate, reverse engineer or modify any part of the Website functionality or the App functionality. WRL makes no claim to ownership of the information or data entered by you on your account, and is not responsible for the accuracy of any information you provide. The WRL logo that appears on the Website and the App are service marks of WRL. No rights are granted to any use of such service marks or any other service mark or trademarks of WRL. Other trademarks and service marks appearing in the Content are the property of their respective owners.
 Section 6. Disclaimer of Warranties; Limitation of Liability
 THE WEBSITE, THE APP, AND THE CONTENT ARE PROVIDED “AS IS,” WITHOUT ANY WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, REGARDING THE WEBSITE, THE APP OR SUCH CONTENT OR YOUR ABILITY OR INABILITY TO USE THE WEBSITE, THE APP OR SAID CONTENT. YOU EXPRESSLY ACKNOWLEDGE THAT YOUR USE OF THE WEBSITE, THE APPAND THE CONTENT IS AT YOUR SOLE RISK. NEITHER WRL NOR ANY OF ITS MEMBERS, SHAREHOLDERS, MANAGERS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, INDEPENDENT CONTRACTORS, REPRESENTATIVES OR ATTORNEYS WILL BE LIABLE TO YOU OR ANY PERSON OR ENTITY CLAIMING THROUGH YOU FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, INCIDENTAL OR OTHER DAMAGES UNDER ANY THEORY OF LAW FOR ANY ERRORS IN, THE USE OF, OR INABILITY TO USE, THE WEBSITE, THE APP OR ANY CONTENT, INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, FOR LOST BUSINESS OR FOR LOST DATA, OR DAMAGE TO ANY COMPUTER SYSTEMS, EVEN IF YOU HAVE ADVISED WRL OR ANY OF ITS MEMBERS, SHAREHOLDERS, MANAGERS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, INDEPENDENT CONTRACTORS, REPRESENTATIVES OR ATTORNEYS ABOUT THE POSSIBILITY OF SUCH DAMAGES.

BETA TESTING: YOU ACKNOWLEDGE AND AGREE THAT THE WEBSITE AND THE APP ARE CURRENTLY UNDER DEVELOPMENT AND ARE PERIODICALLY UNDERGOING TESTING AND CHANGES, AND THAT YOUR USE OF THE WEBSITE AND/OR THE APP MAY BE
SUBJECT TO UNPLANNED INTERRUPTIONS AND ERRORS. As a beta user, you are encouraged to report any errors, defects or questions to support@playersrecleague.com. Please include screenshots and any other relevant information, such as operating system, browser and other features about your system.
 
Section 7. Indemnification
 
You hereby release, and agree to indemnify and hold harmless WRL and its members, shareholders, managers, directors, officers, employees, agents, independent contractors, representatives and attorneys from any and all claims, demands, causes of action, liabilities, damages, costs and expenses, including reasonable attorneys' fees, arising out of your use of or access to the Website, the App, or the Content.
 Section 8. Links to Other Websites
The Website and the App may from time to time include links that would allow you to visit websites or apps owned and operated by parties other than WRL. Such websites and apps and the companies to which they belong are not controlled by or related to any WRL company. WRL makes no representations or warranties nor undertakes any obligation or liability concerning any information, products or services provided or made available on such websites or apps or regarding the quality or acceptability of any persons or entities offering information, products or services, or otherwise referenced on any such websites. WRL has not tested nor makes any representations regarding the correctness, performance or quality of any software found at any such websites. If you access a website other than the Website, it will be at your risk only.
 Section 9. Export of Content and Use of Services
You assume all responsibility for compliance with all laws and regulations of the United States and any other country from which you may access the Website or use the App regarding access, use, export, re-export and import of any Content appearing on or available through the Website or through the  App. You acknowledge and agree that you will not export, re-export or import any Content to any country to which export, re-export or import is restricted under United States law or regulations, that you are not a national of any such country, and that the Content will not be used in the design, development or production of nuclear, chemical or biological weapons. You further assume all responsibility for your use and the use by any associated user of any information, features or services through the Website or through the App.
 
Section 10. Controlling Law, Jurisdiction, Severability and Modification
These Terms of Use and your use of the Website, the App and the Content are governed by and construed in accordance with the laws of the United States and the State of Ohio, excluding its conflict of laws provisions. Any cause of action with respect to the Website, the App, the Content or these Terms of Use must be instituted within one year after the claim or cause of action has risen or be barred and must be brought in a court of competent jurisdiction within Cuyahoga County, Ohio , US. If any provision in these Terms of Use is held or deemed to be entirely or partly invalid or unenforceable by a court of competent jurisdiction, these Terms of Use will be ineffective to the extent of such invalidity or unenforceability without rendering invalid or unenforceable the remaining terms of these Terms of Use. These Terms of Use may not be changed or modified without the written consent of WRL.

`